### PR TITLE
Change time

### PR DESCRIPTION
**Pull request by ia-androsov**
This fixed the blinking for me.

### CODE REVIEW

**Comment by QiangF** [comment]
@ia-androsov Have you notice any increase in CPU? I think put the redisplay in post-command-hook is good enough.

**Comment by ia-androsov** [comment]
@QiangF I didn't notice any increase in CPU, but I like the post-command-hook idea. I'll try it.

**Comment by QiangF** [comment]
FYI. I have used the post-command-hook in my fork. Works well for me so far.
https://github.com/QiangF/emacs-mini-modeline/

**Comment by oxcl** [comment]
tried this pr and the performance hit is very noticeable. emacs becomes almost unusable with this

**Comment by oxcl** [comment]
@QiangF 
trying to use your fork gave me this error
```
⛔ Error (use-package): mini-modeline/:config: Symbol’s value as variable is void: mini-modeline-face-attr
```

**Comment by ia-androsov** [comment]
Change the timer to 0.5 and add:
`(add-hook 'post-command-hook #'mini-modeline-diplay)`.
This also solves my problem.

**Comment by oxcl** [comment]
i will check it out. thanks

**Pull request closed without merging**
